name: List Expired Branches
author: DevOps
description: List expired branches json based on retention policy

inputs:
  days-retention:
    description: 'Retention policy days'
    required: false
    default: 14

outputs:
  has-branches:
    description: 'Has expired branches'
    value: ${{ steps.branches.outputs.has-expired }}
  expired-branches-json:
    description: 'Expired branches'
    value: ${{ steps.branches.outputs.expired-json }}
    
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4
    with:
      fetch-depth: 0 # Fetch all history for all branches and tags
      
  - id: branches
    env:
      days_retention: ${{ inputs.days-retention }}
    shell: bash
    run: |
      ${{ github.action_path }}/gha/expired-branches.sh
