name: List Expired Branches
author: DevOps
description: List expired branches json based on retention policy

# Expected Variables
# ~ $days_retention
# ~ $repository
# ~ $namespace

outputs:
  has-branches:
    description: 'Has expired branches'
    value: ${{ steps.branches.outputs.has-expired-branches }}
  expired-branches-json:
    description: 'Expired branches'
    value: ${{ steps.branches.outputs.expired-branches-json }}
    
runs:
  using: 'composite'
  steps:
  - if: env.days_retention == ''
    env:
      days_retention: 14
    run: |
      echo "days_retention=$days_retention"      

  - shell: bash
    if: env.namespace == '' || env.days_retention == ''
    run: |
      echo "Failed expected variables check."
      exit 1

  - uses: actions/checkout@v4
    with:
      fetch-depth: 0 # Fetch all history for all branches and tags
      
  - id: branches
    shell: bash
    run: |
      bash ${{ github.action_path }}/gha/expired-branches.sh
