name: List Expired Branches
author: DevOps
description: List expired branches json based on retention policy

inputs:
  days-retention:
    description: 'Retention policy days'
    required: false
    default: 14
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  namespace:
    description: 'Helm namespace'
    required: false

outputs:
  has-branches:
    description: 'Has expired branches'
    value: ${{ steps.branches.outputs.has-expired }}
  expired-branches-json:
    description: 'Expired branches'
    value: ${{ steps.branches.outputs.expired-json }}
    
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4
    with:
      fetch-depth: 0 # Fetch all history for all branches and tags

  - name: Authenticate with DEV
    id: authenticate_dev
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: ${{ inputs.aws-region }}

  - id: branches
    env:
      days_retention: ${{ inputs.days-retention }}
    shell: bash
    run: |
      ${{ github.action_path }}/gha/expired-branches.sh
